name: Discord Bot
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          python cheese/sweep_react.py
          python cheese/sweep_check.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}